@startuml

usecase a as "Être affecté à un chantier"
usecase e as "Gérer ses artisans (gérer leurs affectations,\ncalculer automatiquement leur paye)\net ses chantiers"

actor Artisan
actor Entreprise

'Pour aligner les 2 acteurs :
e -[hidden]-> a

Artisan -> a
Entreprise -> e

@enduml